export const SEND_MESSAGE = "SEND_MESSAGE";
export const UPDATE_NEW_MESSAGE_BODY = "UPDATE_NEW_MESSAGE_BODY";
export const ADD_POST = "ADD_POST";
export const UPDATE_NEW_POST_BODY = "UPDATE_NEW_POST_BODY";